# github.com/go-task/task

default:
  cmds:
    - /home/turbo/bin/go build -o golearn main.go 
  env:
    GOOS: linux
    GOARCH: arm
    


deps:
  cmds:
    - /usr/bin/glide up
  env: 
    PATH: /home/turbo/bin/
    GOPATH: /opt/go

upload:
  deps:
    - default
  cmds:
    - scp golearn pi@192.168.1.103:~/golearn
    - ssh pi@192.168.1.103 "/home/pi/golearn"
